language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -U pip pytest
  - pip install --no-deps -r travis-requirements.txt
# command to run tests
script:
- ./src/python robot.py test
